# GRUB for both old (BIOS) and new (UEFI, Secure Boot via shim) PCs.
---
efiBootLoader: "grub"
kernel: "/vmlinuz"
img: "/initrd.img"
timeout: "0"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
efiBootloaderId: "migood"
installEFIFallback: true
